### ISSUE TITLE
Building Projects: "tileAnimation expected" error when building projects that contain a Tile Set

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GMRT-Beta#210]
### Description

When building a project that contains a Tile Set (not necessarily in a Room), the build will fail with the following error:

```
C:/Users/samth/GameMakerProjects/ToDelete/25July2024/tilesets/TileSet1/TileSet1.yy(26,3): GMSC Error: tileAnimation expected.
Core Resources : IDE Message - ProjectLoad_ErrorTitle : ProjectLoad_ErrorMessage ( C:/Users/samth/GameMakerProjects/ToDelete/25July2024/tilesets/TileSet1/TileSet1.yy(26,3): GMSC Error: tileAnimation expected. )
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at yypc.GMAssets.<>c__DisplayClass211_0.<AddProjectToAssets>b__2(ResourceBase _project, Exception _serialiseException) in C:\actions-runner\_work\GMRT\GMRT\YoYoCompilerToolChain\tools\yypc\yypc\GameMaker\GMAssets.cs:line 405
   at YoYoStudio.Resources.ProjectInfo.<>c__DisplayClass23_0.<LoadProject>g__handleFailure|4(Exception exception) in C:\actions-runner\_work\GMRT\GMRT\YoYoCompilerToolChain\tools\CoreResources\CoreResources\Management\ProjectInfo.cs:line 297
   at YoYoStudio.Resources.ProjectInfo.LoadProject(String _path, Boolean _setActive, OnLoadSaveSuccess _onSuccess, OnLoadSaveUpdate _onUpdate, OnLoadSaveFailed _onFailed, Func`2 _shouldShowError) in C:\actions-runner\_work\GMRT\GMRT\YoYoCompilerToolChain\tools\CoreResources\CoreResources\Management\ProjectInfo.cs:line 325
   at yypc.GMAssets.AddProjectToAssets(String _filename, GMAssets _assets, WADHelper _wadHelper, Dictionary`2 resourceHandlerOverrides) in C:\actions-runner\_work\GMRT\GMRT\YoYoCompilerToolChain\tools\yypc\yypc\GameMaker\GMAssets.cs:line 397
   at yypc.Program.CreateProject(String projectPath, String projectDir, String projectName, String projectExtension) in C:\actions-runner\_work\GMRT\GMRT\YoYoCompilerToolChain\tools\yypc\yypc\Program.cs:line 461
   at yypc.Program.BuildProject() in C:\actions-runner\_work\GMRT\GMRT\YoYoCompilerToolChain\tools\yypc\yypc\Program.cs:line 948
   at yypc.Program.DoAction(eBuildAction action) in C:\actions-runner\_work\GMRT\GMRT\YoYoCompilerToolChain\tools\yypc\yypc\Program.cs:line 230
   at yypc.Program.Main(String[] _args) in C:\actions-runner\_work\GMRT\GMRT\YoYoCompilerToolChain\tools\yypc\yypc\Program.cs:line 188
[createdump] Writing minidump for process 16756 to file C:\ProgramData\GameMakerStudio2-Beta\Dumps\gmdump.16756.dmp
[createdump] Dump successfully written in 168ms
``` 

Tested using IDE v2024.800.0.597  Runtime v2024.800.0.620

[Contact Us Package](https://drive.google.com/file/d/12scNX5W4_YsIBHcMiLS1BBNAJvh86f-3/view?usp=sharing)

### Steps To Reproduce

1. Start GameMaker
2. Open/create a project
3. Create a new Tile Set
4. Run the project using GMRT
5. Observe the issue

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 11, Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [X] I have attached my ui.log file

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [X] I have attached a small sample project

**Comment by LukeBrownYoYoGames** [comment]
This should now be fixed in GMRT milestone 0.12.0. This required and update the GMRT's coreresources as tilesets had recently been changed
